### ISSUE TITLE
Vignette FIXMEs

### ISSUE THREAD

**Issue by llrs** [Bioconductor/GSEABase#1]
I have recently noticed that the vignette has the date hard coded ([line 41](https://github.com/Bioconductor/GSEABase/blob/6ffe735b3d3d8c8a9687cc3166bf2601c4d96b66/vignettes/GSEABase.Rnw#L41)), and indeed the last commit done in the vignette seems to be from  Oct 19, 2013. 

It also has some warnings and messages after the title (see the preliminaries under [line 51](https://github.com/Bioconductor/GSEABase/blob/master/vignettes/GSEABase.Rnw#L51)):
```
> ## FIXME: <adjMat> adjacency matrix -- color w. +/- 1
> ## FIXME: limma topTable --> GeneColorSet
> ## w. verbose=TRUE
> library(GSEABase)
> library(hgu95av2.db)
> library(GO.db)
```
In total there are 6 FIXME displaying in the vignette.

**Comment by mtmorgan** [comment]
I won't address the FIXMEs, which serve as notes to future implementors; pull requests welcome of course.

**Comment by llrs** [comment]
I could try to fix them (if I find them useful) but I have troubles understanding them, and I would like to check it with you:

```
## FIXME: <adjMat> adjacency matrix -- color w. +/- 1
## FIXME: limma topTable --> GeneColorSet
## w. verbose=TRUE

## FIXME: GeneSet(AnnotationIdentifier("hgu95av2")) --> non-empty
## FIXME: GeneSet(AnnotationIdentifier("hgu95av2"),
## collectionType=GOCollection()) filters on GOCollection (or KEGG)

## FIXME: BroadCollection default to paste("c", 1:4, sep="")
## FIXME: GeneSetCollection(BroadCollection(), urls=fl); filters on bcCategory
```

My understanding of the FIXME:
 1. To create an adjacency Matrix. What does the color mean? Should a function to plot a hetamap be introduced?
 2. This seems imply to provide a function to create a GeneColorSet from topTable, should it be able to handle DESeq and DESeq2 output? 
 3. Should it load the probes of the hgu95av2 array?
 4. It depends on what should 3. do.

The 5th and 6th I think I don't understand what should do. 

 5. Join only certain GeneSets of the BroadCollection?
 6. Should download by url and then assign the broadCollection?

Many thanks,

BTW I might explore the `getOBOCollection` function that at the moment I am more interested than fixing this.
