### ISSUE TITLE
Faster `incidence()`

### ISSUE THREAD

**Issue by TylerSagendorf** [Bioconductor/GSEABase#9]
Coincidentally, I had written a faster version of `incidence` as part of another function that makes use of matrix multiplication. The key is to only define the positions of nonzero values, since these are less frequent, though it does add an extra `Matrix` import for sparse matrices. This could be rewritten to use regular matrices by starting with a matrix of zeros and using `x.idx` to replace specific values with `1L`; however, I have not tried this, and there may be better practices for dealing with matrices.

```r
library(Matrix)

# y is a "GeneSet" or "GeneSetCollection" object
fast_incidence <- function(y) {
  y <- geneIds(y) # named list of gene sets
  x <- stack(y, drop = TRUE)[, 2L:1L] # columns "ind" (set identifier) and "values" (genes)

  # Convert identifiers to indices (positions of values in sparseMatrix)
  mat.dimnames <- lapply(x, unique)
  x.idx <- mapply(match, x, mat.dimnames)

  mat <- sparseMatrix(i = x.idx[, 1L], j = x.idx[, 2L], x = 1L, dimnames = mat.dimnames)

  return(mat)
}
```

By flipping the columns of the `stack` results, we end up with a `sparseMatrix` with genes as columns and set identifiers as rows. When I was testing this with sets from `msigdb` (v1.10.0), `fast_incidence` was ~25x faster (only took about 2 seconds compared to ~50). It also only used 30.2 MB compared to the 2 GB allocated to the `incidence` results.

**Comment by TylerSagendorf** [comment]
For some reason, `sparseMatrix` converts `x` to `numeric` if it is an `integer`. That would cause `all.equal(as.matrix(fast_incidence(x)), incidence(x))` to be `FALSE`, but the differences between the matrices are all 0.

**Comment by mtmorgan** [comment]
can you provide a simple reproducible example showing the performance difference?

**Comment by TylerSagendorf** [comment]
Not particularly simple due to simulating sets, but here is an example of the speed difference:

```r
library(GSEABase)
library(Matrix)

# y is a "GeneSetCollection" object
fast_incidence <- function(y) {
  y <- geneIds(y) # named list of gene sets
  x <- stack(y, drop = TRUE)[, 2L:1L] # columns "ind" (set identifier) and "values" (genes)

  # Convert identifiers to indices (positions of values in sparseMatrix)
  mat.dimnames <- lapply(x, unique)
  x.idx <- mapply(match, x, mat.dimnames)

  mat <- sparseMatrix(i = x.idx[, 1L], j = x.idx[, 2L], x = 1L, dimnames = mat.dimnames)

  return(mat)
}

# Simulate gene sets of varying sizes ----
set_names <- combn(LETTERS, m = 4L, simplify = FALSE)[1:4000]
set_names <- sapply(set_names, paste, collapse = "")

genes <- combn(letters, m = 4L, simplify = FALSE)[1:5000]
genes <- sapply(genes, paste, collapse = "")
# 5000 genes to distribute into 4000 sets

# For each set, sample between 3 and 50 genes
gene_sets <- lapply(set_names, function(set_i) {
  out <- GeneSet(sample(genes, size = sample(3:50, 1L)))
  setName(out) <- set_i
  return(out)
})
names(gene_sets) <- set_names

# Convert to GeneSetCollection
gene_sets <- as(gene_sets, "GeneSetCollection")

# Compare runtime ----
system.time(x1 <- incidence(gene_sets))
#  user  system elapsed
# 11.22    0.16   11.42

system.time(x2 <- fast_incidence(gene_sets))
# user  system elapsed
# 0.17    0.02    0.19

# Check that they are behaving similarly. Values in x2 are not integers (side-effect of sparseMatrix)
all(x1 - x2 == 0) # TRUE
```

Here, `x1` is 80.8 MB, while `x2` is only 1.9 MB.
The more sparse the incidence matrix ends up being, the greater the difference in time between `fast_incidence` and `incidence`. If I did not limit `genes` to 5000 elements (instead using all 26 choose 4 = 14950 "genes"), `incidence` would take ~70 seconds while the time taken by `fast_incidence` remained the same.

**Comment by mtmorgan** [comment]
Thanks for the example. I experimented with the following, which changes evaluation time from 10s to 1s, but not to .1s. It does not unnecessarily propagate list element names, and constructs the transposed matrix directly. It does not depend on Matrix, so memory allocation is still excessive (but the matrix is as advertised -- an integer matrix of 0 / 1 values). We are assured of compatibility with existing code.

```
GSEABase faster-incidence$ git show
commit 057a93fe79fd05289aa4bea245a39a9444effe4c (HEAD -> faster-incidence)
Author: Martin Morgan <Martin.Morgan@RoswellPark.org>
Date:   Tue Dec 5 18:02:12 2023 -0500

    improve performance of incidence()

    - no need to propagate list element names
    - create 'transposed' matrix directly
    - closes #9

diff --git a/R/methods-GeneSet.R b/R/methods-GeneSet.R
index 5f86f39..2d71da4 100644
--- a/R/methods-GeneSet.R
+++ b/R/methods-GeneSet.R
@@ -185,13 +185,14 @@ setMethod("setdiff",
 ## incidence

 .incidence <- function(gidList, gnmList) {
-    uids <- unique(unlist(gidList))
-    isIn <- lapply(gidList,
-                   function(g, u) match(u, g, nomatch=0),
-                   uids)
-    t(matrix(as.integer(unlist(isIn) > 0),
-             ncol=length(gidList),
-             dimnames=list(uids, unlist(gnmList))))
+    uids <- unique(unlist(gidList, use.names = FALSE))
+    isIn <- lapply(gidList, match, x = uids, nomatch = 0L)
+    matrix(
+        as.integer(unlist(isIn, use.names = FALSE) > 0L),
+        nrow=length(gidList),
+        dimnames=list(unlist(gnmList, use.names = FALSE), uids),
+        byrow = TRUE
+    )
 }

 setMethod("incidence",
```
Is that good enough? Are there other changes to the code that would improve performance?

**Comment by TylerSagendorf** [comment]
Looks good to me. The only other solution would be to initialize a matrix of 0's and then replace specific values with 1 based on their row and column indices, like in my original solution. That way, we aren't having to check if every gene is in every gene set. The time complexity of replacing by index is proportional to `sum(lengths(gidList))` (total number of genes/data points), while the time complexity of the version that checks every gene for a match in every set is proportional to `prod(length(unique(unlist(gidList))), length(gidList))` (product of the dimensions of the incidence matrix). In practice, the former quantity is much smaller than the latter (only equal if every gene set contains the same genes, which would not be good). 

*Note:* The `utils::stack()` function has the added benefit of dropping empty gene sets (not sure if this is ever a problem, though).

```r
.incidence <- function(gidList, gnmList) {
  names(gidList) <- unlist(gnmList, use.names = FALSE)
  gidDF <- stack(gidList)[, 2:1] # flipping columns avoids transpose later
  colnames(gidDF) <- NULL # remove "ind" and "values" as names. Prevents named mat.dimnames
  
  mat.dimnames <- lapply(gidDF, unique)
  mat.dims <- lengths(mat.dimnames) # mat nrow and ncol
  
  # 2D array of positions for nonzero values (gene in set)
  gidIdx <- mapply(match, gidDF, mat.dimnames)
  
  # Initialize a matrix of 0's
  mat <- matrix(data = 0L,
                nrow = mat.dims[1L],
                ncol = mat.dims[2L],
                dimnames = mat.dimnames)
  mat[gidIdx] <- 1L # replace by index
  
  return(mat)
}
```

The speed of this version should be comparable to, if not the same as, my original code.

If the dimensions were flipped with genes as rows, the following would be analogous to your updated version. This is not helpful to the current discussion&mdash;I just thought this was neat :)

```r
.incidence <- function(gidList, gnmList) {
  uids <- unique(unlist(gidList, use.names = FALSE))
  
  # sapply creates a matrix, but the dimensions are flipped
  mat <- sapply(gidList, match, x = uids, nomatch = 0L, simplify = TRUE)
  mat <- (mat > 0L) * 1L # convert to matrix of integers 0 or 1
  
  dimnames(mat) <- list(uids, unlist(gnmList, use.names = FALSE))
  
  return(mat)
}
```

**Comment by mtmorgan** [comment]
Ok, this
```
.incidence <- function(gidList, gnmList) {
    ## vector of genes...
    gene <- unlist(gidList, use.names = FALSE)
    ## ...belonging to each set
    set <- rep(gnmList, lengths(gidList))
    ## all genes & sets
    gene_names <- unique(gene)
    set_names <- unique(gnmList)

    ## create an all-0 set x gene matrix
    incidence <- matrix(
        0L, nrow = length(set_names), ncol = length(gene_names),
        dimnames = list(set_names, gene_names)
    )
    ## update incidence of genes in each set
    incidence[cbind(set, gene)] <- 1L
    incidence
}
```
is only 1/2 the speed as the sparseMatrix solution. It relies on `matrix[<-` to do the matching, based on column names. I modified `gnmList` upstream so that it is actually a character vector of gene set names, e.g.,
```
setMethod("incidence",
          signature=signature(
            x="GeneSet"),
          function(x, ...) {
              args <- c(x, ...)
              .incidence(lapply(args, geneIds),
                         vapply(args, setName, character(1)))
          })
```

**Comment by TylerSagendorf** [comment]
Nice! That is much more elegant than my last solution, too :)

Edit: 1/2 the speed of the sparseMatrix solution, as in twice as fast?

**Comment by mtmorgan** [comment]
[wrote this first based on ad hoc measure...] no, as in twice as slow... about 0.4s versus 0.2 for the sparse solution on my machine. Also the memory consumption is an issue. To me this is 'good enough' for commonly encountered gene sets, and the performance limitations in other parts of the code?

[but then used a formal benchmark...] Actually using microbenchmark the timing is better
```
> microbenchmark::microbenchmark(incidence(gene_sets), fast_incidence(gene_sets), times = 100)
Unit: milliseconds
                      expr      min       lq     mean   median       uq      max
      incidence(gene_sets) 105.2828 109.8797 114.8035 111.8751 120.4635 126.9497
 fast_incidence(gene_sets) 157.9523 161.7667 168.4136 164.1106 166.2363 493.1215
```

**Comment by TylerSagendorf** [comment]
It seems like the fulcrum is between your newest version (faster) and `fast_incidence` (more memory efficient), since the latter has to spend time converting IDs to indices. 

My original reason for wanting to be memory efficient was that I only needed the incidence matrix to calculate intersection sizes with `tcrossprod`, but now I'm not sure if it makes much difference.

In any case, I like your newest version, and I learned how I might improve my own code. Thank you for the discussion!

**Comment by mtmorgan** [comment]
I needed to tweak the details but not the strategy for some of the edge cases documented / tested in existing unit tests, in particular unnamed and duplicate gene sets

```
> incidence(GeneSet(geneIds = letters[1:3]))
     a b c
<NA> 1 1 1
> incidence(GeneSet(setName = "A", geneIds = letters[1:3]), GeneSet(setName = "A", geneIds = letters[1:2]))
  a b c
A 1 1 1
A 1 1 0
```
In retrospect these design decisions seem unlikely to be supported by real use cases and add unnecessary complexity, but it is easier to live with them now than to make changes that potentially break package and user code.
